# Generated by Django 5.1.1 on 2024-10-24 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_picture', models.ImageField(blank=True, null=True, upload_to='animal_pictures/')),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('clinic', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=1000)),
                ('probleme', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='animal_pictures/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='animal_pictures/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='animal_pictures/')),
                ('status', models.CharField(default='En attente', max_length=100)),
                ('status_feedback', models.CharField(default='No', max_length=100)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('viewed', models.CharField(default='No', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_clinique', models.CharField(blank=True, max_length=50, null=True)),
                ('num_ordre', models.IntegerField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('animall_examined', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('dark_mode', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
